// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.IO;
namespace trx2html.Test
{
    /// <summary>
    ///This is a test class for trx2html.ResourceReader and is intended
    ///to contain all trx2html.ResourceReader Unit Tests
    ///</summary>
    [TestClass()]
    public class ResourceReaderTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for LoadTextFromResource (string)
        ///</summary>
        [DeploymentItem("trx2html.exe")]
        [TestMethod()]
        public void LoadTextFromResourceTest()
        {
            string name = "trx2html.css";
            
            string actual = trx2html.Test.trx2html_ResourceReaderAccessor.LoadTextFromResource(name);

            Assert.IsTrue(actual.Length>0, "trx2html.ResourceReader.LoadTextFromResource did not return the expected value.");
            

        }

        /// <summary>
        ///A test for StreamFromResource (string)
        ///</summary>
        [DeploymentItem("trx2html.exe")]
        [TestMethod()]
        public void StreamFromResourceTest()
        {
            string name = "trx2html.css"; // TODO: Initialize to an appropriate value

            Stream actual;

            actual = trx2html.Test.trx2html_ResourceReaderAccessor.StreamFromResource(name);

            Assert.IsTrue(actual.Position==0, "trx2html.ResourceReader.StreamFromResource did not return the expected value.");


        }

    }


}
