// <auto-generated/>
#pragma warning disable 0067, 0108, 0618
[assembly: global::Microsoft.Stubs.Framework.StubsAssembly("trx2html.Test")]
namespace trx2html.Test.Stubs
{
    /// <summary>Mole type of <see cref="trx2html.Test.ResourceReaderTest"/>
    /// .</summary>
    [global::Microsoft.Stubs.Framework.MoleClass(typeof(global::trx2html.Test.ResourceReaderTest))]
    [global::System.CodeDom.Compiler.GeneratedCode("Stubs", "0.19.41103.2")]
    [global::System.Diagnostics.DebuggerDisplay("Mole : ResourceReaderTest")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    public partial class MResourceReaderTest
      : global::Microsoft.Stubs.Framework.MoleBase<global::trx2html.Test.ResourceReaderTest>
    {
        /// <summary>Initializes a new mole</summary>
        public MResourceReaderTest()
        : base()
        {
        }

        /// <summary>Initializes a new mole for the given instance</summary>
        public MResourceReaderTest(global::trx2html.Test.ResourceReaderTest instance)
        : base(instance)
        {
        }

        /// <summary>Define moles for all instances members</summary>
        public static partial class AllInstances
        {
            /// <summary>Sets the mole of <see cref="M:trx2html.Test.ResourceReaderTest.LoadTextFromResourceTest"/>
            /// </summary>
            public static global::Microsoft.Stubs.Framework.StubDelegates.Action<global::trx2html.Test.ResourceReaderTest> LoadTextFromResourceTest
            {
                [global::Microsoft.Stubs.Framework.MoleMethod("LoadTextFromResourceTest", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
                set
                {
                    global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                        ((global::System.Delegate)value, typeof(global::trx2html.Test.ResourceReaderTest), (object)null, "LoadTextFromResourceTest");
                }
            }

            /// <summary>Sets the mole of <see cref="M:trx2html.Test.ResourceReaderTest.StreamFromResourceTest"/>
            /// </summary>
            public static global::Microsoft.Stubs.Framework.StubDelegates.Action<global::trx2html.Test.ResourceReaderTest> StreamFromResourceTest
            {
                [global::Microsoft.Stubs.Framework.MoleMethod("StreamFromResourceTest", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
                set
                {
                    global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                        ((global::System.Delegate)value, typeof(global::trx2html.Test.ResourceReaderTest), (object)null, "StreamFromResourceTest");
                }
            }

            /// <summary>Sets the mole of <see cref="P:trx2html.Test.ResourceReaderTest.TestContext"/>
            /// </summary>
            public static global::Microsoft.Stubs.Framework.StubDelegates.Func<global::trx2html.Test.ResourceReaderTest, global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext> TestContextGet
            {
                [global::Microsoft.Stubs.Framework.MoleMethod("get_TestContext", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
                set
                {
                    global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                        ((global::System.Delegate)value, typeof(global::trx2html.Test.ResourceReaderTest), (object)null, "get_TestContext");
                }
            }

            /// <summary>Sets the mole of <see cref="P:trx2html.Test.ResourceReaderTest.TestContext"/>
            /// </summary>
            public static global::Microsoft.Stubs.Framework.StubDelegates.Action<global::trx2html.Test.ResourceReaderTest, global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext> TestContextSetTestContext
            {
                [global::Microsoft.Stubs.Framework.MoleMethod("set_TestContext", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
                set
                {
                    global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                        ((global::System.Delegate)value, typeof(global::trx2html.Test.ResourceReaderTest), 
                        (object)null, "set_TestContext", typeof(global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext));
                }
            }
        }

        /// <summary>Sets the mole of <see cref="M:trx2html.Test.ResourceReaderTest.#ctor"/>
        /// </summary>
        public static global::Microsoft.Stubs.Framework.StubDelegates.Action<global::trx2html.Test.ResourceReaderTest> Constructor
        {
            [global::Microsoft.Stubs.Framework.MoleMethod(".ctor", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
            set
            {
                global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                    ((global::System.Delegate)value, typeof(global::trx2html.Test.ResourceReaderTest), (object)null, ".ctor");
            }
        }

        /// <summary>Assigns the &apos;NotImplemented&apos; fallback behavior for all methods of the moled type</summary>
        public static void FallbackAsNotImplemented()
        {
            global::trx2html.Test.Stubs.MResourceReaderTest.FallbackBehavior = global::Microsoft.Stubs.Framework.MoleFallbackBehavior.NotImplemented;
        }

        /// <summary>Assigns the fallback behavior for all methods of the moled type</summary>
        public static global::Microsoft.Stubs.Framework.IMoleBehavior FallbackBehavior
        {
            set
            {
                global::Microsoft.Stubs.Framework.MoleFallbackBehavior.AttachToType(typeof(global::trx2html.Test.ResourceReaderTest), value);
            }
        }

        /// <summary>Sets the mole of <see cref="M:trx2html.Test.ResourceReaderTest.LoadTextFromResourceTest"/>
        /// </summary>
        public global::Microsoft.Stubs.Framework.StubDelegates.Action LoadTextFromResourceTest
        {
            [global::Microsoft.Stubs.Framework.MoleMethod("LoadTextFromResourceTest", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
            set
            {
                global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                    ((global::System.Delegate)(global::Microsoft.Stubs.Framework.StubExtensions.UnCurry<global::trx2html.Test.ResourceReaderTest>(value)), 
                    typeof(global::trx2html.Test.ResourceReaderTest), base.Instance, "LoadTextFromResourceTest");
            }
        }

        /// <summary>Sets the mole of <see cref="M:trx2html.Test.ResourceReaderTest.StreamFromResourceTest"/>
        /// </summary>
        public global::Microsoft.Stubs.Framework.StubDelegates.Action StreamFromResourceTest
        {
            [global::Microsoft.Stubs.Framework.MoleMethod("StreamFromResourceTest", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
            set
            {
                global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                    ((global::System.Delegate)(global::Microsoft.Stubs.Framework.StubExtensions.UnCurry<global::trx2html.Test.ResourceReaderTest>(value)), 
                    typeof(global::trx2html.Test.ResourceReaderTest), base.Instance, "StreamFromResourceTest");
            }
        }

        /// <summary>Sets the mole of <see cref="P:trx2html.Test.ResourceReaderTest.TestContext"/>
        /// </summary>
        public global::Microsoft.Stubs.Framework.StubDelegates.Func<global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext> TestContextGet
        {
            [global::Microsoft.Stubs.Framework.MoleMethod("get_TestContext", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
            set
            {
                global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                    ((global::System.Delegate)(global::Microsoft.Stubs.Framework.StubExtensions
                      .UnCurry<global::trx2html.Test.ResourceReaderTest, global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(value)), 
                    typeof(global::trx2html.Test.ResourceReaderTest), base.Instance, "get_TestContext");
            }
        }

        /// <summary>Sets the mole of <see cref="P:trx2html.Test.ResourceReaderTest.TestContext"/>
        /// </summary>
        public global::Microsoft.Stubs.Framework.StubDelegates.Action<global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext> TestContextSetTestContext
        {
            [global::Microsoft.Stubs.Framework.MoleMethod("set_TestContext", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
            set
            {
                global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                    ((global::System.Delegate)(global::Microsoft.Stubs.Framework.StubExtensions
                      .UnCurry<global::trx2html.Test.ResourceReaderTest, global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(value)), 
                    typeof(global::trx2html.Test.ResourceReaderTest), 
                    base.Instance, "set_TestContext", typeof(global::Microsoft.VisualStudio.TestTools.UnitTesting.TestContext));
            }
        }
    }
}
namespace trx2html.Test.Stubs
{
    /// <summary>Mole type of <see cref="trx2html.Test.VersionFinderTest"/>
    /// .</summary>
    [global::Microsoft.Stubs.Framework.MoleClass(typeof(global::trx2html.Test.VersionFinderTest))]
    [global::System.CodeDom.Compiler.GeneratedCode("Stubs", "0.19.41103.2")]
    [global::System.Diagnostics.DebuggerDisplay("Mole : VersionFinderTest")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    public partial class MVersionFinderTest
      : global::Microsoft.Stubs.Framework.MoleBase<global::trx2html.Test.VersionFinderTest>
    {
        /// <summary>Initializes a new mole</summary>
        public MVersionFinderTest()
        : base()
        {
        }

        /// <summary>Initializes a new mole for the given instance</summary>
        public MVersionFinderTest(global::trx2html.Test.VersionFinderTest instance)
        : base(instance)
        {
        }

        /// <summary>Define moles for all instances members</summary>
        public static partial class AllInstances
        {
            /// <summary>Sets the mole of <see cref="M:trx2html.Test.VersionFinderTest.GetVersions"/>
            /// </summary>
            public static global::Microsoft.Stubs.Framework.StubDelegates.Action<global::trx2html.Test.VersionFinderTest> GetVersions
            {
                [global::Microsoft.Stubs.Framework.MoleMethod("GetVersions", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
                set
                {
                    global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                        ((global::System.Delegate)value, typeof(global::trx2html.Test.VersionFinderTest), (object)null, "GetVersions");
                }
            }
        }

        /// <summary>Sets the mole of <see cref="M:trx2html.Test.VersionFinderTest.#ctor"/>
        /// </summary>
        public static global::Microsoft.Stubs.Framework.StubDelegates.Action<global::trx2html.Test.VersionFinderTest> Constructor
        {
            [global::Microsoft.Stubs.Framework.MoleMethod(".ctor", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
            set
            {
                global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                    ((global::System.Delegate)value, typeof(global::trx2html.Test.VersionFinderTest), (object)null, ".ctor");
            }
        }

        /// <summary>Assigns the &apos;NotImplemented&apos; fallback behavior for all methods of the moled type</summary>
        public static void FallbackAsNotImplemented()
        {
            global::trx2html.Test.Stubs.MVersionFinderTest.FallbackBehavior = global::Microsoft.Stubs.Framework.MoleFallbackBehavior.NotImplemented;
        }

        /// <summary>Assigns the fallback behavior for all methods of the moled type</summary>
        public static global::Microsoft.Stubs.Framework.IMoleBehavior FallbackBehavior
        {
            set
            {
                global::Microsoft.Stubs.Framework.MoleFallbackBehavior.AttachToType(typeof(global::trx2html.Test.VersionFinderTest), value);
            }
        }

        /// <summary>Sets the mole of <see cref="M:trx2html.Test.VersionFinderTest.GetVersions"/>
        /// </summary>
        public global::Microsoft.Stubs.Framework.StubDelegates.Action GetVersions
        {
            [global::Microsoft.Stubs.Framework.MoleMethod("GetVersions", global::Microsoft.Stubs.Framework.MoleBindingFlags.PublicInstance)]
            set
            {
                global::Microsoft.Stubs.Framework.MoleRuntime.SetStubPublicInstance
                    ((global::System.Delegate)(global::Microsoft.Stubs.Framework.StubExtensions.UnCurry<global::trx2html.Test.VersionFinderTest>(value)), 
                    typeof(global::trx2html.Test.VersionFinderTest), base.Instance, "GetVersions");
            }
        }
    }
}
namespace trx2html.Test.Stubs
{
    /// <summary>Stub type of <see cref="trx2html.Test.ResourceReaderTest"/>
    /// .</summary>
    [global::Microsoft.Stubs.Framework.StubClass(typeof(global::trx2html.Test.ResourceReaderTest))]
    [global::System.CodeDom.Compiler.GeneratedCode("Stubs", "0.19.41103.2")]
    [global::System.Serializable]
    [global::System.Diagnostics.DebuggerDisplay("Stub = ResourceReaderTest")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    public partial class SResourceReaderTest
      : global::trx2html.Test.ResourceReaderTest
      , global::Microsoft.Stubs.Framework.IStub
      , global::Microsoft.Stubs.Framework.IPartialStub
    {
        /// <summary>Initializes a new instance</summary>
        public SResourceReaderTest()
        {
            this.InitializeStub();
        }

        /// <summary>Gets or sets a value that indicates if the base method should be called instead of the fallback behavior</summary>
        public bool CallBase
        {
            get
            {
                return this.callBase;
            }
            set
            {
                this.callBase = value;
            }
        }

        /// <summary>Initializes a new instance of type SResourceReaderTest</summary>
        private void InitializeStub()
        {
        }

        /// <summary>Gets or sets the fallback behavior.</summary>
        public global::Microsoft.Stubs.Framework.IStubBehavior InstanceFallbackBehavior
        {
            get
            {
                return global::Microsoft.Stubs.Framework.StubFallbackBehavior.GetValueOrCurrent(this.defaultStub);
            }
            set
            {
                this.defaultStub = value;
            }
        }

        private bool callBase;

        private global::Microsoft.Stubs.Framework.IStubBehavior defaultStub;
    }
}
namespace trx2html.Test.Stubs
{
    /// <summary>Stub type of <see cref="trx2html.Test.VersionFinderTest"/>
    /// .</summary>
    [global::Microsoft.Stubs.Framework.StubClass(typeof(global::trx2html.Test.VersionFinderTest))]
    [global::System.CodeDom.Compiler.GeneratedCode("Stubs", "0.19.41103.2")]
    [global::System.Serializable]
    [global::System.Diagnostics.DebuggerDisplay("Stub = VersionFinderTest")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    public partial class SVersionFinderTest
      : global::trx2html.Test.VersionFinderTest
      , global::Microsoft.Stubs.Framework.IStub
      , global::Microsoft.Stubs.Framework.IPartialStub
    {
        /// <summary>Initializes a new instance</summary>
        public SVersionFinderTest()
        {
            this.InitializeStub();
        }

        /// <summary>Gets or sets a value that indicates if the base method should be called instead of the fallback behavior</summary>
        public bool CallBase
        {
            get
            {
                return this.callBase;
            }
            set
            {
                this.callBase = value;
            }
        }

        /// <summary>Initializes a new instance of type SVersionFinderTest</summary>
        private void InitializeStub()
        {
        }

        /// <summary>Gets or sets the fallback behavior.</summary>
        public global::Microsoft.Stubs.Framework.IStubBehavior InstanceFallbackBehavior
        {
            get
            {
                return global::Microsoft.Stubs.Framework.StubFallbackBehavior.GetValueOrCurrent(this.defaultStub);
            }
            set
            {
                this.defaultStub = value;
            }
        }

        private bool callBase;

        private global::Microsoft.Stubs.Framework.IStubBehavior defaultStub;
    }
}
